<?php

	//rename this file to conf.php

	const CONSUMER_KEY = 'YOUR_CONSUMER_KEY';
	const CONSUMER_SECRET = 'YOUR_CONSUMER_SECRET';
	const ACCESS_TOKEN = 'YOUR_ACCESS_TOKEN';
	const ACCESS_TOKEN_SECRET = 'YOUR_ACCESS_TOKEN_SECRET';
	const OAUTH_CALLBACK = 'URL_TO_THIS_AUTH_DIRECTORY/callback.php';

	const SESSION_NAME = 'ANY_NAME_FOR_SESSION';
	const COOKIE_NAME = 'ANY_NAME_FOR_COOKIE';
	const COOKIE_EXPIRY_TIME = 86400 * 30;  //30 days

	const DATA_SCRAPING_PERIOD = 3600 * 1; //1 hr